module.exports = {
  BOT_TOKEN: process.env.BOT_TOKEN,
  BOT_OWNER_ID: process.env.BOT_OWNER_ID,
  TICKET_CHANNEL_ID: process.env.TICKET_CHANNEL_ID,
  DUNGEON_CHANNEL_ID: process.env.DUNGEON_CHANNEL_ID,
  LEVELING_CHANNEL_ID: process.env.LEVELING_CHANNEL_ID,
  GOLD_CHANNEL_ID: process.env.GOLD_CHANNEL_ID,
  DUNGEON_OFFERS_CHANNEL_ID: process.env.DUNGEON_OFFERS_CHANNEL_ID,
  ACCOUNT_CHANNEL_ID: process.env.ACCOUNT_CHANNEL_ID,
  ARK_COINS_CHANNEL_ID: process.env.ARK_COINS_CHANNEL_ID,
  ASH_COINS_CHANNEL_ID: process.env.ASH_COINS_CHANNEL_ID,
  ARK_RATE_PER_100K: Number(process.env.ARK_RATE_PER_100K) || 6,
};
